Added nl_nl.json
MrCrayfish/MrCrayfishGunMod pull request #141
Opened 2021-03-26 14:53 UTC by Autovw

Dutch translations.

2021-03-26 23:35 UTC, Ocelot5836 requested changes
You should probably not minimize it to keep files readable.

2021-03-27 06:38 UTC, MrCrayfish commented
Will merge once formatted.

2021-03-27 08:30 UTC, Autovw commented
Fixed it.

2021-03-27 11:29 UTC, MrCrayfish commented
Thank you!

2021-03-27 11:29 UTC, merged